version: 2.1
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: Agent scan
          command: |
            echo "DIR = $(pwd)"
            ls -alh
            echo "START SCANNING"
            curl -LJO https://github.com/threatrix/threat-matrix/releases/download/agent-release-latest/threat-agent-latest.jar
            java -jar threat-agent-latest.jar --env=dev --app-name=threat-matrix-2-gh-actions --tags=circleci ./