version: 2.1
jobs:
  build:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: First step
          command: |
            echo "DIR = $(pwd)"
            ls -alh