version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2204:2024.11.1
    steps:
      - checkout
      - run:
          name: Agent scan
          command: |
            echo "--------------START SCANNING---------------"
            echo $CIRCLE_REPOSITORY_URL
            echo $CIRCLE_BRANCH
            echo $CIRCLE_PROJECT_USERNAME
            echo $CIRCLE_PROJECT_REPONAME
            printenv > host.env
            echo "---------------------------------------------------------------"
            cat host.env
            echo "---------------------------------------------------------------"
            docker run -v $(pwd):/app --env-file=host.env threatrix/threat-agent --env=dev --verbose --app-name=threat-matrix-2 --tags=circleci-image ./
