name: 'ThreatAgent scan'

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run agent
        env:
          THREATRIX_API_KEY: ${{ secrets.THREATRIX_API_KEY }}
          THREATRIX_OID: ${{ secrets.THREATRIX_OID }}
          THREATRIX_EID: ${{ secrets.THREATRIX_EID }}
          THREATCENTER_SERVER: ${{ secrets.THREATCENTER_SERVER }}
        run: |
          curl -LJO https://github.com/threatrix/threat-matrix/releases/download/agent-release-latest/threat-agent-latest.jar
          java -jar threat-agent-latest.jar useAgentV2=false --env=dev --tags=actions image:sonarqube:10-community